// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrjXRvj9B35c5D8RNHt1LQqAYTmziGxo',
    appId: '1:294118948508:web:c8649b39e01c66ad63f759',
    messagingSenderId: '294118948508',
    projectId: 'my-smart-budget',
    authDomain: 'my-smart-budget.firebaseapp.com',
    storageBucket: 'my-smart-budget.firebasestorage.app',
    measurementId: 'G-MVZF2SS9GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLDWYM9-93SE5I3DZb3th4P0U_PHKDQY',
    appId: '1:294118948508:android:3998219682a6a56e63f759',
    messagingSenderId: '294118948508',
    projectId: 'my-smart-budget',
    storageBucket: 'my-smart-budget.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMUj7nCfrdY7tjRa7PYjPmW1idsC4jkw',
    appId: '1:294118948508:ios:df6bf0534fd4044663f759',
    messagingSenderId: '294118948508',
    projectId: 'my-smart-budget',
    storageBucket: 'my-smart-budget.firebasestorage.app',
    iosBundleId: 'com.example.smartbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMUj7nCfrdY7tjRa7PYjPmW1idsC4jkw',
    appId: '1:294118948508:ios:df6bf0534fd4044663f759',
    messagingSenderId: '294118948508',
    projectId: 'my-smart-budget',
    storageBucket: 'my-smart-budget.firebasestorage.app',
    iosBundleId: 'com.example.smartbudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsrjXRvj9B35c5D8RNHt1LQqAYTmziGxo',
    appId: '1:294118948508:web:64f57705c5119e3063f759',
    messagingSenderId: '294118948508',
    projectId: 'my-smart-budget',
    authDomain: 'my-smart-budget.firebaseapp.com',
    storageBucket: 'my-smart-budget.firebasestorage.app',
    measurementId: 'G-MQ3CRLEDMS',
  );
}
